peval_system/base/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve



app_name = 'base'

urlpatterns =[
    path("profile", views.view_profile, name='view_profile'),
    path("view_perf_info/", views.view_perf_info, name='view_perf_info'),
    
    path("add_educ_att", views.add_educ_att, name='add_educ_att'),
    path("add_workexp", views.add_workexp, name='add_workexp'),
    path("add_pub", views.add_pub, name='add_pub'),
    path("add_acc_events", views.add_acc_events, name='add_acc_events'),
    path("add_res_grants", views.add_res_grants, name='add_res_grants'),
    path("add_licexam", views.add_licexam, name='add_licexam'),
    path("add_trainsem", views.add_trainsem, name='add_trainsem'),
    path("add_confwork", views.add_confwork, name='add_confwork'),
    path("add_extserv", views.add_extserv, name='add_extserv'),
    path("add_facultyservrec", views.add_facultyservrec, name='add_facultyservrec'),

    path("edit_educ_att/<int:pk>/", views.edit_educ_att, name='edit_educ_att'),
    path("edit_workexp/<int:pk>/", views.edit_workexp, name='edit_workexp'),
    path("edit_acc_events/<int:pk>/", views.edit_acc_events, name='edit_acc_events'),
    path("edit_pub/<int:pk>/", views.edit_pub, name='edit_pub'),
    path("edit_res_grants/<int:pk>/", views.edit_res_grants, name='edit_res_grants'),
	path("edit_licexam/<int:pk>/", views.edit_licexam, name='edit_licexam'),
    path("edit_trainsem/<int:pk>/", views.edit_trainsem, name='edit_trainsem'),
    path("edit_confwork/<int:pk>/", views.edit_confwork, name='edit_confwork'),
    path("edit_extserv/<int:pk>/", views.edit_extserv, name='edit_extserv'),
    path("edit_facservrec/<int:pk>/", views.edit_facservrec, name='edit_facservrec'),
    
    path("delete_educ_att/<int:pk>/", views.delete_educ_att, name='delete_educ_att'),
    path("delete_workexp/<int:pk>/", views.delete_workexp, name='delete_workexp'),
    path("delete_acc_events/<int:pk>/", views.delete_acc_events, name='delete_acc_events'),
    path("delete_pub/<int:pk>/", views.delete_pub, name='delete_pub'),
    path("delete_res_grants/<int:pk>/", views.delete_res_grants, name='delete_res_grants'),
    path("delete_licexam/<int:pk>/", views.delete_licexam, name='delete_licexam'),
    path("delete_trainsem/<int:pk>/", views.delete_trainsem, name='delete_trainsem'),
    path("delete_confwork/<int:pk>/", views.delete_confwork, name='delete_confwork'),
    path("delete_extserv/<int:pk>/", views.delete_extserv, name='delete_extserv'),
    path("delete_facservrec/<int:pk>/", views.delete_facservrec, name='delete_facservrec'),

    path("admin_dash/", views.admin_dash, name='admin_dash'),
    path("edit_user/<int:pk>/", views.edit_user, name='edit_user'),
    path("edit_pers_info/<int:pk>/", views.edit_pers_info, name='edit_pers_info'),
    path("update_set/<int:pk>/", views.update_set, name='update_set'),
    path("add_facultyservrec_clerk/", views.add_facultyservrec_clerk, name='add_facultyservrec_clerk'),
    path("faculty_load/", views.faculty_load, name='faculty_load'),

    path("unithead_dashboard", views.unit_dash_view, name='unithead_dashboard'),
    path("unithead_dashboard_table", views.unit_table_view,name="unithead_dashboard_table"),
    path("unithead_faculty_list", views.unit_faculty_view, name='unithead_faculty_list'),
    path("unithead_role_assignment", views.unit_assignment_view, name='unithead_role_assignment'),
    path("unithead_pending_approvals", views.unithead_pending_approvals, name='unithead_pending_approvals'),

    path("accomView", views.accomView, name="accomView"),
    path("deptchair_dashboard", views.dept_dash_view, name='deptchair_dashboard'),
    path("deptchair_dashboard_table", views.dept_table_view,name="deptchair_dashboard_table"),
    path("deptchair_faculty_list", views.dept_faculty_view, name='deptchair_faculty_list'),
    path("deptchair_role_assignment", views.dept_assignment_view, name='deptchair_role_assignment'),
    path("deptchair_pending_approvals", views.deptchair_pending_approvals, name='deptchair_pending_approvals'),
    path("deptchair_add_clerk", views.dept_clerk_view, name='deptchair_add_clerk'),
    path("export_excel_accom", views.export_excel_accom, name="export_excel_accom"),

    path("approve_educ_att/<int:pk>", views.approve_educ_att, name="approve_educ_att"),
    path("approve_work_exp/<int:pk>", views.approve_work_exp, name="approve_work_exp"),
    path("approve_acc_events/<int:pk>", views.approve_acc_events, name="approve_acc_events"),
    path("approve_pub/<int:pk>", views.approve_pub, name="approve_pub"),
    path("approve_res_grant/<int:pk>", views.approve_res_grant, name="approve_res_grant"),
    path("approve_licexam/<int:pk>", views.approve_licexam, name="approve_licexam"),
    path("approve_trainsem/<int:pk>", views.approve_trainsem, name="approve_trainsem"),
    path("approve_confwork/<int:pk>", views.approve_confwork, name="approve_confwork"),
    path("approve_extserv/<int:pk>", views.approve_extserv, name="approve_extserv"),
    path("approve_facservrec/<int:pk>", views.approve_facservrec, name="approve_facservrec"),
    path("assign_deptchair/<int:pk>", views.assign_deptchair, name="assign_deptchair"),
    
    path("verify_educ_att/<int:pk>", views.verify_educ_att, name="verify_educ_att"),
    path("verify_work_exp/<int:pk>", views.verify_work_exp, name="verify_work_exp"),
    path("verify_acc_events/<int:pk>", views.verify_acc_events, name="verify_acc_events"),
    path("verify_pub/<int:pk>", views.verify_pub, name="verify_pub"),
    path("verify_res_grant/<int:pk>", views.verify_res_grant, name="verify_res_grant"),
    path("verify_licexam/<int:pk>", views.verify_licexam, name="verify_licexam"),
    path("verify_trainsem/<int:pk>", views.verify_trainsem, name="verify_trainsem"),
    path("verify_confwork/<int:pk>", views.verify_confwork, name="verify_confwork"),
    path("verify_extserv/<int:pk>", views.verify_extserv, name="verify_extserv"),
    path("verify_facservrec/<int:pk>", views.verify_facservrec, name="verify_facservrec"),
    path("assign_unithead/<int:pk>", views.assign_unithead, name="assign_unithead"),
    

]

urlpatterns += static(settings.UPLOAD_URL, document_root=settings.UPLOAD_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.)

peval_system/peval_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('allauth.urls')),
    path('', include('base.urls', namespace='base')),
    path('', include('users.urls', namespace='users'))

]

peval_system/users/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
#from django.conf.urls import url
from django.urls import path
from .views import *



app_name = 'users'

urlpatterns =[
	path("", views.login, name='login'),
	path("login", views.login, name='login'),
	path("create_user", views.create_user, name='create_user'),
	path('logout', views.logout_user, name='logout_user'),
	
]

peval_system/base/models.py
from email.policy import default
from django.db import models
from users.models import User
from datetime import datetime

SEMESTERCHOICES=(
    ('1', 'First Semester'),
    ('2', 'Second Semester'),
    ('3', 'Mid Year'),
)

DAYCHOICES=(
    ('1', 'Monday'),
    ('2', 'Tuesday'),
    ('3', 'Wednesday'),
    ('4', 'Thursday'),
    ('5', 'Friday'),
    ('6', 'Saturday'),
    ('7', 'Sunday'),
)

PUBLICATIONTYPECHOICES=(
    ('1', 'Peer-reviewed journal article'),
    ('2', 'Book/Monograph'),
    ('3', 'Edited/peer-reviewed book chapter'),
    ('4', 'Peer-reviewed conference paper publication'),
)

PUBLISHERTYPECHOICES=(
    ('1', 'Commercial'),
    ('2', 'Learned society and association'),
)

LOCATIONPUBLISHERCHOICES=(
    ('1', 'Local'),
    ('2', 'International'),
)

PRESENTATIONTYPECHOICES=(
    ('1', 'Oral Presentation'),
    ('2', 'Poster Presentation'),
)

CONFERENCELOCATIONCHOICES=(
    ('1', 'International/in-house'),
    ('2', 'Local/regional'),
    ('3', 'National'),
    ('4', 'International')
)

ACCOMPLISHMENTREPORTCHOICES=(
    ('Academic Affairs', 'Academic Affairs'),
    ('Student Concerns', 'Student Concerns'),
    ('International Linkages', 'International Linkages'),
    ('Conferences/Workshops', 'Conferences/Workshops'),
    ('Extension Services (Trainings/Seminars/Workshops conducted)', 'Extension Services (Trainings/Seminars/Workshops conducted)'),
    ('Research Grants', 'Research Grants'),
    ('Publications', 'Publications'),
    ('Planned Activities and Announcements', 'Planned Activities and Announcements')
)

ACADEMICYEARCHOICES=(
    ('1', '2020-2021'),
    ('2', '2021-2022'),
    ('3', '2022-2023'),
    ('4', '2023-2024'),
    ('5', '2024-2025'),
    ('6', '2025-2026'),
)



class EducationalAttainment(models.Model):
    user = models.ForeignKey(User, related_name='EducationalAttainment', on_delete = models.CASCADE)
    institution = models.CharField(max_length=240)
    degree = models.CharField(max_length=240)
    certification = models.CharField(max_length=240)
    major = models.CharField(max_length=240)
    specialization = models.CharField(max_length=240)
    degree_type = models.CharField(max_length=10)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    proof = models.FileField(upload_to ='uploads/educatt_proof/')
    is_approved = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400, blank=True)

class WorkExperience(models.Model):
    user = models.ForeignKey(User, related_name='WorkExperience', on_delete = models.CASCADE)
    position = models.CharField(max_length=240)
    employer_name = models.CharField(max_length=240)
    is_within = models.BooleanField(default=False)    
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    #Check if max_length should be bigger
    description = models.CharField(max_length=500)
    proof = models.FileField(upload_to ='uploads/workexp/')
    is_approved = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400, blank=True)

class AccomplishmentsEvents(models.Model):
    user = models.ForeignKey(User, related_name='AccomplishmentsEvents', on_delete = models.CASCADE)
    accomplishment_title = models.CharField(max_length=240)
    type = models.CharField(max_length=240, choices=ACCOMPLISHMENTREPORTCHOICES, default=ACCOMPLISHMENTREPORTCHOICES[0])
    description = models.CharField(max_length=500)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    date_created = models.DateField(auto_now_add=True)
    proof = models.FileField(upload_to ='uploads/acc_events/')
    is_verified = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400, blank=True)

class Publications(models.Model):
    user = models.ForeignKey(User, related_name='Publications', on_delete = models.CASCADE)
    is_dpsm = models.BooleanField(default=False)
    publication_name = models.CharField(max_length=240)
    citation = models.CharField(max_length=240)
    url = models.URLField(max_length = 240)
    date_published = models.DateField(null=True, blank=True)
    # proof = models.FileField(upload_to ='uploads/')

    co_author_DPSM = models.ManyToManyField(User)
    #co_author_nonDPSM = models.CharField(max_length=240)
    publication_type = models.CharField(max_length=240, choices=PUBLICATIONTYPECHOICES, default=PUBLICATIONTYPECHOICES[0])
    conference_name = models.CharField(max_length=240)

    publisher_name = models.CharField(max_length=240)
    publisher_type = models.CharField(max_length=240, choices=PUBLISHERTYPECHOICES, default=PUBLISHERTYPECHOICES[0])
    publisher_location = models.CharField(max_length=20, choices=LOCATIONPUBLISHERCHOICES, default=LOCATIONPUBLISHERCHOICES[0])
    volume_issue_num = models.CharField(max_length=240)
    publication_url = models.URLField(max_length=250)
    publication_doi = models.CharField(max_length=240)
    publication_isbn = models.CharField(max_length=240)

    is_isi = models.BooleanField(default=False)
    is_elseviers_scopus = models.BooleanField(default=False)
    is_ched_recognized = models.BooleanField(default=False)
    other_collection = models.CharField(max_length=240)
    is_funded_up_gaa = models.BooleanField(default=False)
    uiob = models.CharField(max_length=500)

    proof_publication = models.FileField(upload_to ='uploads/pubs/pub')
    proof_utilization = models.FileField(upload_to ='uploads/util')
    is_presented = models.BooleanField(default=False)

    is_approved = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400, blank=True)

class ResearchGrants(models.Model):
    user = models.ForeignKey(User, related_name='ResearchGrants', on_delete = models.CASCADE)
    co_author_DPSM = models.ManyToManyField(User)
    #co_author_nonDPSM = models.CharField(max_length=240)
    is_dpsm = models.BooleanField(default=False)
    research_name = models.CharField(max_length=240)
    sponsor_name = models.CharField(max_length=240)
    grant_amount = models.CharField(max_length=240)
    project_start_date = models.DateField(null=True, blank = True)
    project_end_date = models.DateField(null=True, blank = True)
    actual_start_date = models.DateField(null=True, blank=True)
    actual_end_date = models.DateField(null=True, blank=True)
    research_progress = models.CharField(max_length=240)

    proof = models.FileField(upload_to ='uploads/research_grants')
    is_approved = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400, blank=True)


class LicensureExam(models.Model):
    user = models.ForeignKey(User, related_name='LicensureExam', on_delete = models.CASCADE)
    exam_name = models.CharField(max_length=240)
    rank = models.CharField(max_length=240)
    license_number = models.CharField(max_length=20)
    date_exam = models.DateField(null=True, blank=True)

    proof = models.FileField(upload_to ='uploads/lic_exam')
    is_approved = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400)

class TrainingSeminars(models.Model):
    user = models.ForeignKey(User, related_name='TrainingSeminars', on_delete = models.CASCADE)
    training_name = models.CharField(max_length=240)
    role = models.CharField(max_length=240)
    remarks = models.CharField(max_length=240)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    proof = models.FileField(upload_to ='uploads/train_sem')
    is_approved = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    comments_remarks = models.CharField(max_length=400, blank=True)

# class AddAccomplishments(models.Model):
#     position = models.CharField(max_length=240)
#     organization_name = models.CharField(max_length=240)
#     start_date = models.DateField(null=True, blank=True)
#     end_date = models.DateField(null=True, blank=True)
#     is_within = models.BooleanField(default=False)
#     contributions_profession = models.CharField(max_length=240)
#     contributions_nation = models.CharField(max_length=240)
#     contributions_world = models.CharField(max_length=240)
#     description = models.CharField(max_length=240)
#     proof = models.FileField(upload_to ='uploads/')
#     is_approved = models.BooleanField(default=False)
#     is_verified = models.BooleanField(default=False)
#     comments_remarks = models.CharField(max_length=400)



class ConferenceWorkshops(models.Model):
    user = models.ForeignKey(User, related_name='ConferenceWorkshops', on_delete = models.CASCADE)
    event_name = models.CharField(max_length=240)
    paper_title = models.CharField(max_length=240)
    presentation_type = models.CharField(max_length=20, choices=PRESENTATIONTYPECHOICES, default=PRESENTATIONTYPECHOICES[0])
    conference_title = models.CharField(max_length=240)
    organizer_name = models.CharField(max_length=240)
    conference_location = models.CharField(max_length=240, choices=CONFERENCELOCATIONCHOICES, default=CONFERENCELOCATIONCHOICES[0])
    conference_venue = models.CharField(max_length=240)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

peval_system/base/templates/_baseform.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

peval_system/base/templates/_faculty_navbar.html
{% load static %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" id="logout" href="{% url 'users:logout_user' %}">Logout</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'base:view_profile' %}">Credentials</a>
        </li>              
       

      </ul>
    </div>
    <div style="float: right; width: 500px; text-align: right;"">
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'base:view_perf_info' %}">
          {{user.first_name}}
          {{user.last_name}}
          ({{user.get_role_display}})  
        </a>  
        {% endif %}  
     </div>
     <div style="width: 50px;">
    </div>
  </nav>

peval_system/base/templates/admin_dash.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
{% include '_admin_navbar.html' %}
<div class="container mt-3">           
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Email</th>
          <th>Department</th>
          
          <th>Update User</th>
          
          <!--<th>Update SET</th>-->
        </tr>
      </thead>
      <tbody>
        {% for users in Users %}
        <!-- {% if user.is_authenticated %} -->
        <tr>
          <td>{{ users.first_name }}</td>
          <td>{{ users.last_name }}</td>
          <td>{{ users.email }}</td>
          <td>{{ users.get_department_display }}</td>
          
          <td><a href="{% url 'base:edit_user' pk=users.pk %}" role="button"> Edit </a></td>   
          
          <!--<td><a href="{% url 'base:update_set' pk=users.pk %}" role="button">Update</button></td>-->
        </tr>
        <!-- {% endif %} -->
      {% endfor%}
      </tbody>
    </table>
  </div>

</div>

</body>
</html>

peval_system/base/templates/sidebar_deptchair.html
{% load static %}
    <style>
        .sidebar {
            height: 100%; /* Full-height: remove this if you want "auto" height */
            width: 185px; /* Set the width of the sidebar */
            position: fixed; /* Fixed Sidebar (stay in place on scroll) */
            z-index: 1; /* Stay on top */
            left: 0;
            margin-top: 70px;
            background-color: rgb(0, 48, 30, 0.8); /* Black */
            overflow-x: hidden; /* Disable horizontal scroll */
            padding-top: 30px;
        }

            /* The navigation menu links */
        .sidebar a {
            padding: 8px 10px 8px 16px;
            text-decoration: none;
            font-size: 15px;
            color: #000000;
            display: block;
        }
  
         /* When you mouse over the navigation links, change their color */
        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar a:active {
            color: #87906F;
            background-color: #87906F;
            
        }
         
    </style>
  
    <section class="login-clean min-vh-100" > 
        <div class="sidebar">
            <a href="{% url 'base:deptchair_dashboard' %}" role="button">Dashboard</a>
            <a href="{% url 'base:deptchair_faculty_list' %}" role="button">Faculty List</a>
            <a href="{% url 'base:deptchair_pending_approvals' %}" role="button">Pending Approvals</a>
            <a href="{% url 'base:deptchair_role_assignment' %}" role="button">Role Assignment</a>
            <a href="{% url 'base:deptchair_add_clerk' %}" role="button">Add Clerk</a>
        </div>       
        <br>
    </section> 

peval_system/base/templates/sidebar_unithead.html
{% load static %}
    <style>
        .sidebar {
            height: 100%; /* Full-height: remove this if you want "auto" height */
            width: 185px; /* Set the width of the sidebar */
            position: fixed; /* Fixed Sidebar (stay in place on scroll) */
            z-index: 1; /* Stay on top */
            left: 0;
            margin-top: 70px;
            background-color: rgb(0, 48, 30, 0.8); /* Black */
            overflow-x: hidden; /* Disable horizontal scroll */
            padding-top: 30px;
        }

            /* The navigation menu links */
        .sidebar a {
            padding: 8px 10px 8px 16px;
            text-decoration: none;
            font-size: 15px;
            color: #000000;
            display: block;
        }
  
         /* When you mouse over the navigation links, change their color */
        .sidebar a:hover {
            color: #f1f1f1;
        }

        .sidebar a:active {
            color: #87906F;
            background-color: #87906F;
            
        }
         
    </style>
  
    <section class="login-clean min-vh-100" > 
        <div class="sidebar">
            <a href="{% url 'base:unithead_dashboard' %}" role="button">Dashboard</a>
            <a href="{% url 'base:unithead_faculty_list' %}" role="button">Faculty List</a>
            <a href="{% url 'base:unithead_pending_approvals' %}" role="button">Pending Approvals</a>
            <a href="{% url 'base:unithead_role_assignment' %}" role="button">Role Assignment</a>
        </div>       
        <br>
    </section> 

peval_system/base/templates/unithead_dashboard_table.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"> 

        <!-- <link rel="stylesheet" href="{% static '/css/style_dept_head.css' %"> -->
        <style>
            .content{
                margin-left: 225px;
                margin-top: -650px;
            }
            table {
                border-collapse: collapse;
                border-spacing: 0;
                width: 95%;
                height:5%;
                border: 1px solid #ddd;
            }
            th {
                background-color: #AFAFAF;
                text-align: center;
                padding: 4px;
            }
            td {
                padding: 3.5px;
            }
        </style>

</head>
<body>
	 {% include '_navbar.html' %}
     {% include 'sidebar_unithead.html' %}
    
<div class="content">
     <h2>Accomplishment Count</h2>
            <table id="filter_table">
                <tr>
                    <th style="background-color: white; text-align: left">Start Date</th>
                    <th style="background-color: white; text-align: left">End Date</th>
                    <th style="background-color: white; text-align: left">   </th>
                </tr>
                <tr>
                    <td><input type="date" name="start_date" style="width:225px"></td>
                    <td><input type="date" name="end_date" style="width:225px"></td>
                    <td><button id="filter_button" style="background-color:#0D6EFD"><font style="color:white">Filter</font></button></td>
                </tr>
                <tr>
                    <td>
                        Current view:
                        <a role="button" id="graph_view" href="{% url 'base:unithead_dashboard' %}">Overview</a>
                        <button id="list_view" style="background-color:#006100"><font style="color:white">Full List</font></button>
                    </td>
                    <td>
                        Sort by: 
                        <select name="dept_unit" id="dept_unit">
                            <option value="1">Name of Faculty</option>
                            <option value="2">Accomplishment</option>
                            <option value="3">Accomplishment Type</option>
                            <option value="4">Start Date (Latest)</option>
                            <option value="5">End Date (Latest)</option>
                        </select>
                    </td>
                    <td>
                        <a href="{% url 'base:export_excel_accom' %}" role="button" id="export_button"style="background-color:#0D6EFD;align: right;width: 165px;padding:5px"><font style="color:white">Export as Excel file</font></a>
                    </td>
                </tr>
            </table>

            <br>
            <input type="text" id="search_bar" onkeyup = "searchTable()" placeholder="Search" style="width:285px">

            <br><br>
            <table id="accomplishment_table">
                <tr>
                    <th style="width:200px">Name of Faculty</th>
                    <th style="width:450px">Accomplishment</th>
                    <th style="width:250px">Accomplishment Type</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
                <tbody>
                    {% for accomplishment in accomplishments %}
                    {% if user.department == accomplishment.user.department %}
                <tr>
                    <td>{{ accomplishment.user.first_name }} {{ accomplishment.user.last_name }}</td>
                    <td>{{ accomplishment.accomplishment_title }}</td>
                    <td>{{ accomplishment.type }}</td>
                    <td>{{ accomplishment.start_date}}</td>
                    <td>{{ accomplishment.end_date }}</td>
                </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
                
            </table>
</div>

<script type="text/javascript">
    function searchTable() {
			var filter = document.getElementById("search_bar").value.toUpperCase();
			var table = document.getElementById("accomplishment_table");
			var tr = table.getElementsByTagName("tr");

			for (var i = 1; i < tr.length; i++) {
				var td = tr[i].getElementsByTagName("td")[0];
				var txtValue = td.innerText;
				if (txtValue.toUpperCase().includes(filter)) {
					tr[i].style.display = "";
				}
				else {
					tr[i].style.display = "none";
				}
			}
	}

</script>

</body>
</html>